# Generated by Django 5.0.6 on 2025-01-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_document_uploaded_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
