# Generated by Django 5.0.6 on 2025-01-15 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_at', models.DateTimeField(auto_now_add=True)),
                ('answer_content', models.CharField(blank=True, max_length=255)),
                ('ask_at', models.DateTimeField(auto_now_add=True)),
                ('ask_content', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
