# Generated by Django 5.0.6 on 2025-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ask_content',
            field=models.TextField(),
        ),
    ]
